name: Generate Snake Animation

on:
  # Dijalankan secara otomatis setiap 24 jam
  schedule:
    - cron: "0 0 * * *" 
  
  # Memungkinkan kamu menjalankan script ini secara manual kapan saja
  workflow_dispatch:
  
  # Dijalankan setiap kali ada push ke branch main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Men-generate animasi ular (svg)
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Mendorong (push) file svg yang sudah jadi ke branch bernama 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
